# Generated by Django 3.0.2 on 2020-01-26 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0002_auto_20200126_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='color',
            field=models.CharField(choices=[('0', ''), ('1', 'Green'), ('2', 'Yellow'), ('3', 'Blue'), ('4', 'Black'), ('5', 'White')], default='0', max_length=20),
        ),
    ]
